package DomainLayer;

public enum Genre {
    ACTION, ADVENTURE, ACTION_COMEDY,
    COMEDY, CRIME,
    DOCUMENTARY, DRAMA, DUTCH,
    FAMILY, FANTASY,
    HORROR,
    ROMANCE, REALITY,
    SCIENCE_FICTION,
    THRILLER
}
